import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "@/context/Provider";
import Header from "@/components/layout/header/Header";
import Sidebar from "@/components/layout/sidebar/Sidebar";
import { getAllCategories } from "@/lib/api/blog";
import { auth } from "@/auth";
import { Footer } from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const session = await auth();
  const res = await getAllCategories();
  if (!res.success) return <div>Fail to get all categories (layout.tsx)</div>
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} w-full min-h-full bg-surface-base antialiased`}
    >
      <body className="w-full min-h-full flex flex-col">
        <Provider>
          <Header/>
          <div className="w-full min-h-full grow flex flex-row">
            <Sidebar session={session} initialCategories={res.data} />
            <main className="grow min-h-full flex flex-col items-center justify-between">
              {children}
              <Footer/>
            </main>
          </div>
        </Provider>
      </body>
    </html>
  );
}
